#+TITLE: Collision detection and physics system demonstration
#+AUTHOR: Dustin Condon
#+DATE: 20 Nov 2022

* Introduction
This is a simple non-interactable demo of a 2D collision detection and
constraint-based collision response system.

The collision detection system operates on three shape primitives:
convex polygon, circle, and line segment. The collision system
generates contacts when two shapes are found to collide. Collision
contact are comprised of a collision normal and collision points.

The physics system turns these contacts into contact constraints,
which are then used in the collision response system. The collision
response system iteratively applies impulses to the rigid bodies
involved in a constraint in order to try and have all the constriants
become met by the end of the simulation timestep.

If two objects are penetrating, an extra corrective impulse is applied
to them which is proportional to their depth. This is done to try and
seperate them.

The implementation and structure of a few key features are based off
of Erin Catto's [[https://box2d.org/][Box2D]]--namely:

1. How friction is calculated
2. The structure and language of a collision "fixture"
3. The iterative, constraint-based collision resolution
    
Note that there are many feature not present in this implementation
that are found in Box2D. For instance, there is currently no
"warm-starting"; that is, the constraints from the previous frame are
not used in the current frame speed up iterative processes of
determining impulses, as they are in Box2D

* Dependencies
Building this project will require the rust compiler be installed in
the environment. The version used to build is specicially rust version
1.65, although previous version may work.

The graphics used in this demo are handled by SDL2, which is also required to be
installed to run this project.

* How to run
Navigate to the directory containing this README in a terminal and
type "cargo run" and the physics_tester and its dependencies
will build and then run a non-interactable physics scene.
